# default configuration, override in config/local-development.toml

# port to listen on
port = 8080

# whether the app runs behind a trusted proxy
proxy = false

# application name used for logging and service namespace
name = 'myservice'

# number of worker processes to spawn, 0 = autodetect
num_workers = 1

# log level to output at
log_level = 'debug'

# where to write logs, can be file path or stdout/err
log_output = 'stdout'
